### ISSUE TITLE
Build Error: WebpackError

### ISSUE THREAD

**Issue by Manav-SM** [rathesDot/rathes.me#371]
Getting a Build Error: WebpackError multiple times while using Gatsby build locally. The website builds successfully locally but it fails to deploy on Cloudflare pages and Netlify due to this error.

Here is the error.

```
warn WebpackError: Unsafe builtin usage fs.existsSync
    at gatsby-starter-default/node_modules/browserslist/node.js:38:1
    at gatsby-starter-default/node_modules/browserslist/node.js:46:1
    at gatsby-starter-default/node_modules/browserslist/node.js:305:1
    at gatsby-starter-default/node_modules/browserslist/node.js:223:1
    at gatsby-starter-default/node_modules/browserslist/index.js:411:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.statSync
    at gatsby-starter-default/node_modules/browserslist/node.js:38:1
    at gatsby-starter-default/node_modules/browserslist/node.js:46:1
    at gatsby-starter-default/node_modules/browserslist/node.js:305:1
    at gatsby-starter-default/node_modules/browserslist/node.js:223:1
    at gatsby-starter-default/node_modules/browserslist/index.js:411:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.existsSync
    at gatsby-starter-default/node_modules/browserslist/node.js:38:1
    at gatsby-starter-default/node_modules/browserslist/node.js:317:1
    at gatsby-starter-default/node_modules/browserslist/node.js:49:1
    at gatsby-starter-default/node_modules/browserslist/node.js:305:1
    at gatsby-starter-default/node_modules/browserslist/node.js:223:1
    at gatsby-starter-default/node_modules/browserslist/index.js:411:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.statSync
    at gatsby-starter-default/node_modules/browserslist/node.js:38:1
    at gatsby-starter-default/node_modules/browserslist/node.js:317:1
    at gatsby-starter-default/node_modules/browserslist/node.js:49:1
    at gatsby-starter-default/node_modules/browserslist/node.js:305:1
    at gatsby-starter-default/node_modules/browserslist/node.js:223:1
    at gatsby-starter-default/node_modules/browserslist/index.js:411:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.readFileSync
    at gatsby-starter-default/node_modules/browserslist/node.js:85:1
    at gatsby-starter-default/node_modules/browserslist/node.js:319:1
    at gatsby-starter-default/node_modules/browserslist/node.js:49:1
    at gatsby-starter-default/node_modules/browserslist/node.js:305:1
    at gatsby-starter-default/node_modules/browserslist/node.js:223:1
    at gatsby-starter-default/node_modules/browserslist/index.js:411:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  83 |
  84 | function parsePackage (file) {
> 85 |   var config = JSON.parse(fs.readFileSync(file))
     | ^
  86 |   if (config.browserlist && !config.browserslist) {
  87 |     throw new BrowserslistError(
  88 |       '`browserlist` key instead of `browserslist` in ' + file

warn WebpackError: Unsafe builtin usage fs.existsSync
    at gatsby-starter-default/node_modules/browserslist/node.js:38:1
    at gatsby-starter-default/node_modules/browserslist/node.js:328:1
    at gatsby-starter-default/node_modules/browserslist/node.js:49:1
    at gatsby-starter-default/node_modules/browserslist/node.js:305:1
    at gatsby-starter-default/node_modules/browserslist/node.js:223:1
    at gatsby-starter-default/node_modules/browserslist/index.js:411:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.existsSync
    at gatsby-starter-default/node_modules/browserslist/node.js:38:1
    at gatsby-starter-default/node_modules/browserslist/node.js:332:8
    at gatsby-starter-default/node_modules/browserslist/node.js:49:1
    at gatsby-starter-default/node_modules/browserslist/node.js:305:1
    at gatsby-starter-default/node_modules/browserslist/node.js:223:1
    at gatsby-starter-default/node_modules/browserslist/index.js:411:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }

warn WebpackError: Unsafe builtin usage fs.existsSync
    at gatsby-starter-default/node_modules/browserslist/node.js:38:1
    at gatsby-starter-default/node_modules/browserslist/node.js:199:1
    at gatsby-starter-default/node_modules/browserslist/node.js:49:1
    at gatsby-starter-default/node_modules/browserslist/node.js:197:1
    at gatsby-starter-default/node_modules/browserslist/index.js:433:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:54:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/browsers.js:42:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:103:1
    at gatsby-starter-default/node_modules/autoprefixer/lib/autoprefixer.js:117:1
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:133:17
    at gatsby-starter-default/node_modules/postcss/lib/lazy-result.js:131:1
    at gatsby-starter-default/node_modules/postcss/lib/processor.js:33:1
    at gatsby-starter-default/gatsby-ssr.js:20:43
    at gatsby-starter-default/.cache/api-runner-ssr.js:53:41

  36 |     return filenessCache[file]
  37 |   }
> 38 |   var result = fs.existsSync(file) && fs.statSync(file).isFile()
     | ^
  39 |   if (!process.env.BROWSERSLIST_DISABLE_CACHE) {
  40 |     filenessCache[file] = result
  41 |   }
```

To replicate

1.  Clone this repository
2. Use the terminal to navigate into the project folder and install dependencies using <strong>npm install</strong>
3. After the packages finish installing run the command <strong>gatsby build</strong>

**Comment by rathesDot** [comment]
Hey, I'm terribly sorry for this late reply. I didn't notice this issue for some reason. Are you getting this error on the lastest master build, too?

This is a warning from webpack because of the latest major gatsby version. But it shouldn't block deployment. https://rathes.me is still building on Netlify currently (still with the warnings though)
